// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mo2EmZqg72vNjUGSKK3KkTOBmy5Mswo',
    appId: '1:154926205994:web:a8eb56ad9dae7a6d18c753',
    messagingSenderId: '154926205994',
    projectId: 'caki-f98dd',
    authDomain: 'caki-f98dd.firebaseapp.com',
    storageBucket: 'caki-f98dd.firebasestorage.app',
    measurementId: 'G-51HZGXQQBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2nbhQnBB2AQYhjJ76a8edgh0x5J-U54',
    appId: '1:154926205994:android:d0b0366dcf9000c618c753',
    messagingSenderId: '154926205994',
    projectId: 'caki-f98dd',
    storageBucket: 'caki-f98dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGUMxDI-R32Si042U8avxY-ZLCn3mx7TY',
    appId: '1:154926205994:ios:3d89465e0de79dc318c753',
    messagingSenderId: '154926205994',
    projectId: 'caki-f98dd',
    storageBucket: 'caki-f98dd.firebasestorage.app',
    androidClientId: '154926205994-05c2iqofradabhjihsc1cdpvn8tnp3v3.apps.googleusercontent.com',
    iosClientId: '154926205994-g3ol5sa9vpspqcktmstbumnjeegj4t45.apps.googleusercontent.com',
    iosBundleId: 'com.example.cakiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGUMxDI-R32Si042U8avxY-ZLCn3mx7TY',
    appId: '1:154926205994:ios:3d89465e0de79dc318c753',
    messagingSenderId: '154926205994',
    projectId: 'caki-f98dd',
    storageBucket: 'caki-f98dd.firebasestorage.app',
    androidClientId: '154926205994-05c2iqofradabhjihsc1cdpvn8tnp3v3.apps.googleusercontent.com',
    iosClientId: '154926205994-g3ol5sa9vpspqcktmstbumnjeegj4t45.apps.googleusercontent.com',
    iosBundleId: 'com.example.cakiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-mo2EmZqg72vNjUGSKK3KkTOBmy5Mswo',
    appId: '1:154926205994:web:c2373840f285207a18c753',
    messagingSenderId: '154926205994',
    projectId: 'caki-f98dd',
    authDomain: 'caki-f98dd.firebaseapp.com',
    storageBucket: 'caki-f98dd.firebasestorage.app',
    measurementId: 'G-X4F3N3JEVR',
  );
}
